
main = sp? stmt*

stmt = def sp?

def = def__fun

def__fun = "fn" sp+ fun__name sp? "(" fun__params ")" expr

fun__name = id
fun__params = ( (param ",")* param ","? )?
param = sp? id sp?

expr = sp? ( block / call / id / const / empty ) sp?

block = "{" block__body "}"
block__body = ((expr ";")* expr ";"? )?

call = id sp? "(" call__arg ")"
call__arg = ( (arg ",")* arg ","? )?
arg = sp? expr sp?

id = ~"(\w|_)(\w|\d|_)*"

const = ~"\d+"

sp = space+
space = ~"(\s|\n)"

empty = ""
